name: CI
on:
  push:
    branches: [ master ]

jobs:
  build-root:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: asdf-vm/actions/install@v1
    - run: asdf plugin list
    - run: asdf current

  build-sub-only:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
    - uses: actions/checkout@v2
    - uses: asdf-vm/actions/install@v1
    - run: asdf plugin list
    - run: asdf current terraform

  build-sub-override:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: helm3
    steps:
    - uses: actions/checkout@v2
    - uses: asdf-vm/actions/install@v1
    - run: asdf plugin list
    - run: asdf current helm
